language: node_js
node_js:
- '8'
script:
- npm run-script build
before_script:
- cd web-app
- npm install
- npm run init
after_success:
- cd build
- echo $FTP_PASSWORD
- "$FTP_PASSWORD"
- find . -type f -exec curl --ftp-create-dirs -T {} -u $FTP_USER:$FTP_PASSWORD ftp://s16.mydevil.net/public_nodejs/public/\{\}
  \;
notifications:
  email:
    secure: RNbnVY+IgHfNoIXcpiEOMpTqgonDlVbGNIW4utJi1kOHjs4jXcsXwUlxDaLsOvL3OrDzf6wT8Ph9vRfATg3/N2Sgk/EhGeHO4gwu0ISimhPs7OtqPJAnLD9B6ALtEoi05cpjHaTwI1/oqrssxb8CXD87YkonokdXSEj9Jzq17Cz3zNJW/oS5+Km9s+daU54KKyA5A7cDQ4j9ccD8+ZzVgol/NQm23nw1TnusikP0h1TESsQU6uuv44GPa0NwWtH4eJ9nXp9NE5WWbG6JyMgeyGhr1rIhMGa7gSbnj/9IxXHi4shGIN5DtbtPFOE/SPCCD5f7yWfgagVB3astHQfB82KkqKynl6geqHvakgDZXO9gAl08xEOAnMibn8K/6vqcZasAyAb4owIvWKGwSAypbiKUxjpfM9PVcByGwYKnBq3j5xTVrsDHW8AHC5Rnfp1RGoa1Twagt5FGLTcLZeqsNOjCZ7mQz1eaKpZNWh2fk1V7mksGhT+Ness1LApgAdZQhqNLiD5nRaAu/bzIjwcGRwaIDMX/INrQLta8TPuI3+OJ3hLmBQK9fIGPzBy5H3hbAay0SSN/RX3v83GO8z4u9XCvfoC1HI2+GiKA7binTaAyhSSb92SQw971AUKyI3x/Ffal1F/tTYJQvpH0jSYnQFTRcCe0VABBz8ZodE9pyXM=
env:
  global:
  - secure: ko8ExmQkQp/owIM5ClvqnRhDluhVmHE0wxNjA2v7QQxOIyzC9zTEf/dmNBKrhQazQ4QBAqjOe+WUUVXaZkuGWk4HFzpugD5MwNbwKOyXFCUX7CybXk8JXgMtSFiaCEiybFQiBSfokgzlxK/ZV+UFJVV8M+lBK8mjiDK78nUyvmgXfv96i2y3Is3fkyXxK861beC4+AG3seKx3+wBU6PtYl5sfat170nf4dbDoHMoImgwHcqOB8QP1a+Mfz3YYVvzy3Ax6fK2MbcLW/9/d2Jzs4qDpnrrQq3xuIPI8EYuTQu/Hfme8T09I7TW0AV2DQM8tTMn8QYwm4ab9GvwQ21LBn1rBr0RqSpNU2o+COcuXF898NN6bQy1jbgK+HFxr33/sULPDF2HwfFrNloKqITuUJoX6x0zd2Q2HI4hVb2OaI8XmnWu9HdR+8CnYoceZqCXY+hgrLO/wc+NoxvH1x26vABxZFU/DiGukT9/QFBZ8bl9o8fMNzCZyInTGnCgfm290/6EEeTbTJMKwtyX+nuxLRa/W364iATthFM4zPlKceYyDpnODhga3D8yTvJqPTNFX30Mv1X7DJ7nNEtetXUiJ3MH1PrjD5r53wz2/hYUnA2B5hoj0xzY90lWS/IUlWA88OBL9fkZ7E6V1dn/R54v+53VSMP66udx9c6DAOL7Srk=
  - secure: NygMWWA565FurMmbgZy9YL+2V2GqyJd3AyQepbNTdGTVee2z5sXtfEqYGq1f4UzWixHVNeifCz0xEaCo2fk6WPI6Mnuv4QaCBkl/6hJjspymumowx/JY9pIpvBK+KcDf8sMAtCgSLcypp8tO2oTG9uimx3W+6Mf1o2wvqSubzQ7lpsk4zW8M/KaWtgN9w1Tjto4IgH1xbHbDIPd4qBpcI3uWBAZA6xQSdsHp5tZuUgc2pMd2F+476oIqblljp9mgplaAFBb1651mEsCmth6QKCZ1pCKmAtGKhxfBi8ticqHNp0CFnI0D5XC/yQX+yl3iQsd6wbqNIN7LV2Z88MSpEPckQC4Eiz1KF0IDiTC1CL1j+yvY5iq+hV+qdoWSqsh/yjeEI4ZrF8bFJyk5p6L0bsx31VB368zUesyL4HDvBVKeBt32ReMI/XOFWhrJmym+HsrOtUfMJ9E0c/DEadkn7J2nLmDeyClr5lZKqy63OpGao/7c/48r4vJaDoV96f5+zOofenaXVjgKXD1hTacYzsyGE0bNMZwxK4gKXMKIJrJFMz9X6Eq1oOIAim5wlpfUL1PFXT0k9rG0vJWk5XTDbx2lZQHLZnle7mDzhTt4G7iI0W7qBUwYVp+WG3j9XB8gJD/2FJXrKRjufsZY/qUpPN8QCQ9CTtao6/8Y32LchJ8=
